### ISSUE TITLE
Stop VGC/VGK

### ISSUE THREAD

**Issue by eMerchant717** [YasInvolved/RitoVanguardManager#1]
add stop functions

**Comment by YasInvolved** [comment]
It's already added in recent commit. Thanks for noticing.

**Comment by eMerchant717** [comment]
im getting no config error? does this one works for valorant vanguard? or just LoL?

**Comment by YasInvolved** [comment]
> im getting no config error? does this one works for valorant vanguard? or just LoL?

For now it's working only in League but I'm going to add support for other riot games really soon. I just need to temporarily install Valorant and test if this is working the same as league
